### ISSUE TITLE
met Cannot read property 'on' of undefined error

### ISSUE THREAD

**Issue by xzyaoi** [shuhei/Compare#2]
When i run 'react-native run-ios', and in the packager window, the process terminated by an error

```
...
/Users/XXX/Compare/node_modules/.1.0.1@yeoman-welcome

Cannot read property 'on' of undefined
```

I've Googled that but found nothing helps.

**Comment by shuhei** [comment]
Which versions of node and npm do you use?

**Comment by shuhei** [comment]
I don't have `.1.0.1@yeoman-welcome` in my `node_modules`. It's just `yeoman-welcome`. I guess something is wrong in your `node_modules`.

**Comment by xzyaoi** [comment]
@shuhei

I am using node v6.9.1 and npm v3.10.8

**Comment by shuhei** [comment]
Hmm, so they are not outdated. What if you delete `node_modules` and `npm
install` again? Also, when you generate a react-native app by yourself,
does it work?

**Comment by xzyaoi** [comment]
hmmm, i've tried it.

I deleted it and re installed the node_modules but it did not work.

I generate the react-native app by myself and it could run.

So I was really wondering what's the problem with it.

**Comment by shuhei** [comment]
Thanks for trying out! I might be related to react-native upgrade. I created this project with an older version of react-native and upgraded it recently.

By the way, what OS do you use?

**Comment by xzyaoi** [comment]
I am using Mac OS X Sierra with XCode 8 (beta)

BTW, which version of react-native were you using when you created this project? Maybe I should try this version?

**Comment by shuhei** [comment]
Hmm, Sierra. Mine is still El Capitan. I made this project with react-native 0.27.2.

But `.1.0.1@yeoman-welcome` is weird. Would you mind pasting the result of `npm ls`?

**Comment by xzyaoi** [comment]
After so many days debugging...

I found this problem was due to the CNPM, a replacement of npm. CNPM seems making soft links of node_modules while the react native packager does not recognize. so this problem happens.

**Comment by shuhei** [comment]
@stevefermi Thanks for investigating! I haven't heard of CNPM. Good to know.

So, can we close this issue now?

**Comment by xzyaoi** [comment]
Sure! Thanks for your answering!
