### ISSUE TITLE
Version with Bars

### ISSUE THREAD

**Issue by indivisable** [shuhei/Compare#3]
Would you happen to have the sample code for this version? Just interested in seeing how you did the animation.

![image](https://cloud.githubusercontent.com/assets/22860891/22006403/52dcd542-dc30-11e6-907c-643af1e24a6b.png)

Awesome project and reference/talk glad to have found!

**Comment by shuhei** [comment]
Hi, I happened to keep the version with a branch called `bars`! The code of the bars look like this:

https://github.com/shuhei/Compare/blob/bars/ios/components/HourlyChart.js

**Comment by indivisable** [comment]
Thats perfect, its great to see it in the simpler form! I'll go ahead and close this. Thanks++

**Comment by shuhei** [comment]
My pleasure :-)
